version: "2"
languages:
  Python: true
  JavaScript: true
checks:
  similar-code:
    config:
      threshold: 40
plugins:
  radon:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.py"
exclude_paths:
  - 'callisto_core/tests/'
  - 'callisto_core/notification/migrations/'
  - 'callisto_core/delivery/migrations/'
  - 'callisto_core/accounts/tests/'
  - 'callisto_core/wizard_builder/tests/'
  - 'callisto_core/wizard_builder/migrations/'
